export default [
	{
		name: "Afghanistan",
		topLevelDomain: [".af"],
		alpha2Code: "AF",
		alpha3Code: "AFG",
		callingCodes: ["93"],
		capital: "Kabul",
		altSpellings: ["AF", "Afġānistān"],
		region: "Asia",
		subregion: "Southern Asia",
		population: 27657145,
		latlng: [33, 65],
		demonym: "Afghan",
		area: 652230,
		gini: 27.8,
		timezones: ["UTC+04:30"],
		borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
		nativeName: "افغانستان",
		numericCode: "004",
		currencies: [
			{
				code: "AFN",
				name: "Afghan afghani",
				symbol: "؋",
			},
		],
		languages: [
			{
				iso639_1: "ps",
				iso639_2: "pus",
				name: "Pashto",
				nativeName: "پښتو",
			},
			{
				iso639_1: "uz",
				iso639_2: "uzb",
				name: "Uzbek",
				nativeName: "Oʻzbek",
			},
			{
				iso639_1: "tk",
				iso639_2: "tuk",
				name: "Turkmen",
				nativeName: "Türkmen",
			},
		],
		translations: {
			de: "Afghanistan",
			es: "Afganistán",
			fr: "Afghanistan",
			ja: "アフガニスタン",
			it: "Afghanistan",
			br: "Afeganistão",
			pt: "Afeganistão",
			nl: "Afghanistan",
			hr: "Afganistan",
			fa: "افغانستان",
		},
		flag: "https://restcountries.eu/data/afg.svg",
		regionalBlocs: [
			{
				acronym: "SAARC",
				name: "South Asian Association for Regional Cooperation",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "AFG",
	},
	{
		name: "Brazil",
		topLevelDomain: [".br"],
		alpha2Code: "BR",
		alpha3Code: "BRA",
		callingCodes: ["55"],
		capital: "Brasília",
		altSpellings: [
			"BR",
			"Brasil",
			"Federative Republic of Brazil",
			"República Federativa do Brasil",
		],
		region: "Americas",
		subregion: "South America",
		population: 206135893,
		latlng: [-10, -55],
		demonym: "Brazilian",
		area: 8515767,
		gini: 54.7,
		timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
		borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
		nativeName: "Brasil",
		numericCode: "076",
		currencies: [
			{
				code: "BRL",
				name: "Brazilian real",
				symbol: "R$",
			},
		],
		languages: [
			{
				iso639_1: "pt",
				iso639_2: "por",
				name: "Portuguese",
				nativeName: "Português",
			},
		],
		translations: {
			de: "Brasilien",
			es: "Brasil",
			fr: "Brésil",
			ja: "ブラジル",
			it: "Brasile",
			br: "Brasil",
			pt: "Brasil",
			nl: "Brazilië",
			hr: "Brazil",
			fa: "برزیل",
		},
		flag: "https://restcountries.eu/data/bra.svg",
		regionalBlocs: [
			{
				acronym: "USAN",
				name: "Union of South American Nations",
				otherAcronyms: ["UNASUR", "UNASUL", "UZAN"],
				otherNames: [
					"Unión de Naciones Suramericanas",
					"União de Nações Sul-Americanas",
					"Unie van Zuid-Amerikaanse Naties",
					"South American Union",
				],
			},
		],
		cioc: "BRA",
	},
	{
		name: "Lesotho",
		topLevelDomain: [".ls"],
		alpha2Code: "LS",
		alpha3Code: "LSO",
		callingCodes: ["266"],
		capital: "Maseru",
		altSpellings: ["LS", "Kingdom of Lesotho", "Muso oa Lesotho"],
		region: "Africa",
		subregion: "Southern Africa",
		population: 1894194,
		latlng: [-29.5, 28.5],
		demonym: "Mosotho",
		area: 30355,
		gini: 52.5,
		timezones: ["UTC+02:00"],
		borders: ["ZAF"],
		nativeName: "Lesotho",
		numericCode: "426",
		currencies: [
			{
				code: "LSL",
				name: "Lesotho loti",
				symbol: "L",
			},
			{
				code: "ZAR",
				name: "South African rand",
				symbol: "R",
			},
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
			{
				iso639_1: "st",
				iso639_2: "sot",
				name: "Southern Sotho",
				nativeName: "Sesotho",
			},
		],
		translations: {
			de: "Lesotho",
			es: "Lesotho",
			fr: "Lesotho",
			ja: "レソト",
			it: "Lesotho",
			br: "Lesoto",
			pt: "Lesoto",
			nl: "Lesotho",
			hr: "Lesoto",
			fa: "لسوتو",
		},
		flag: "https://restcountries.eu/data/lso.svg",
		regionalBlocs: [
			{
				acronym: "AU",
				name: "African Union",
				otherAcronyms: [],
				otherNames: [
					"الاتحاد الأفريقي",
					"Union africaine",
					"União Africana",
					"Unión Africana",
					"Umoja wa Afrika",
				],
			},
		],
		cioc: "LES",
	},
	{
		name: "Nauru",
		topLevelDomain: [".nr"],
		alpha2Code: "NR",
		alpha3Code: "NRU",
		callingCodes: ["674"],
		capital: "Yaren",
		altSpellings: [
			"NR",
			"Naoero",
			"Pleasant Island",
			"Republic of Nauru",
			"Ripublik Naoero",
		],
		region: "Oceania",
		subregion: "Micronesia",
		population: 10084,
		latlng: [-0.53333333, 166.91666666],
		demonym: "Nauruan",
		area: 21,
		gini: null,
		timezones: ["UTC+12:00"],
		borders: [],
		nativeName: "Nauru",
		numericCode: "520",
		currencies: [
			{
				code: "AUD",
				name: "Australian dollar",
				symbol: "$",
			},
			{
				code: "(none)",
				name: null,
				symbol: "$",
			},
		],
		languages: [
			{
				iso639_1: "en",
				iso639_2: "eng",
				name: "English",
				nativeName: "English",
			},
			{
				iso639_1: "na",
				iso639_2: "nau",
				name: "Nauruan",
				nativeName: "Dorerin Naoero",
			},
		],
		translations: {
			de: "Nauru",
			es: "Nauru",
			fr: "Nauru",
			ja: "ナウル",
			it: "Nauru",
			br: "Nauru",
			pt: "Nauru",
			nl: "Nauru",
			hr: "Nauru",
			fa: "نائورو",
		},
		flag: "https://restcountries.eu/data/nru.svg",
		regionalBlocs: [],
		cioc: "NRU",
	},
	{
		name: "Finland",
		topLevelDomain: [".fi"],
		alpha2Code: "FI",
		alpha3Code: "FIN",
		callingCodes: ["358"],
		capital: "Helsinki",
		altSpellings: [
			"FI",
			"Suomi",
			"Republic of Finland",
			"Suomen tasavalta",
			"Republiken Finland",
		],
		region: "Europe",
		subregion: "Northern Europe",
		population: 5491817,
		latlng: [64, 26],
		demonym: "Finnish",
		area: 338424,
		gini: 26.9,
		timezones: ["UTC+02:00"],
		borders: ["NOR", "SWE", "RUS"],
		nativeName: "Suomi",
		numericCode: "246",
		currencies: [
			{
				code: "EUR",
				name: "Euro",
				symbol: "€",
			},
		],
		languages: [
			{
				iso639_1: "fi",
				iso639_2: "fin",
				name: "Finnish",
				nativeName: "suomi",
			},
			{
				iso639_1: "sv",
				iso639_2: "swe",
				name: "Swedish",
				nativeName: "svenska",
			},
		],
		translations: {
			de: "Finnland",
			es: "Finlandia",
			fr: "Finlande",
			ja: "フィンランド",
			it: "Finlandia",
			br: "Finlândia",
			pt: "Finlândia",
			nl: "Finland",
			hr: "Finska",
			fa: "فنلاند",
		},
		flag: "https://restcountries.eu/data/fin.svg",
		regionalBlocs: [
			{
				acronym: "EU",
				name: "European Union",
				otherAcronyms: [],
				otherNames: [],
			},
		],
		cioc: "FIN",
	},
];
